Helpdesk process for SR2024
srobo/runbook pull request #202
Opened 2024-03-19 21:06 UTC by RealOrangeOne

This PR updates the helpdesk procedures, both to bring them in line with how we currently run it, and to update those processes for SR2024.

These changes are still very much draft, and have not been reviewed by the rest of the Kit Team (& committee). There's no point reviewing this PR until this message is removed.

2024-03-27 19:53 UTC, raccube commented on docs/competition/team-support/diagrams/kit-return-desk-flow.svg
nit: last box is missing a space

2024-03-28 20:42 UTC, raccube requested changes

2024-03-28 20:55 UTC, RealOrangeOne commented on docs/competition/team-support/helpdesk.md
> +Teams are allowed to request that the name on the scoreboard is changed. This is an action that needs to be performed by a volunteer that is trained to use the SRComp software or GitHub repository.
I think we probably should, yes. At least to require having more than 1 competitor per team suggesting it.

2024-03-30 18:27 UTC, raccube approved these changes

2024-03-31 11:01 UTC, merged